name: "${project.name}"
main: no.atc.floyd.bukkit.who.WhoPlugin
version: "${project.version}"
website: "${project.url}"
author: FloydATC
softdepend: [PermissionsEx]
description: "${project.description}"

commands:
  who:
    description: Show a list of online players
    usage: /<command>
  playerlist:
    description: Show a list of online players
    usage: /<command>
  list:
    description: Show a list of online players
    usage: /<command>
  online:
    description: Show a list of online players
    usage: /<command>
  afk:
    description: Tag yourself as Away From Keyboard (toggle)
    usage: /<command> [<message>]
  hide:
    description: Hide yourself from the online player list (toggle)
    usage: /<command>
  tell:
    description: Send a private message
    usage: /<command> <player> <message>
  msg:
    description: Send a private message
    usage: /<command> <player> <message>
  whisper:
    description: Send a private message
    usage: /<command> <player> <message>
